version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/gjcourt/drift

linters:
  default: standard
  enable:
    - revive
    - misspell
    - gocritic

  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: unused-parameter
    gocritic:
      enabled-tags:
        - diagnostic
        - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
